name: Build Fusion Module

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  checks:
    uses: bellflight/github-actions/avr_build_and_push_container.yml
    with:
      container_name: fusion